### PR TITLE
Add : Support AlchemySerialization with generics and inheritance 

### PR DESCRIPTION
**Pull request by Akeit0**
This works as follows.

スクリーンショット 2024-03-03 011151

```cs
using System;
using System.Collections.Generic;
using Alchemy.Serialization;
using UnityEngine;


[AlchemySerialize]
public partial class InheritedSerializeTestBase<T> : MonoBehaviour
{
    [AlchemySerializeField, NonSerialized] HashSet<T> set;
}
```

```cs

// <auto-generated/>


partial class InheritedSerializeTestBase<T> : global::UnityEngine.ISerializationCallbackReceiver
{
    void global::UnityEngine.ISerializationCallbackReceiver.OnAfterDeserialize()
    {
        SerializationCallback_AlchemyImpl(false);
        if (this is global::Alchemy.Serialization.IAlchemySerializationCallbackReceiver receiver)
            receiver.OnAfterDeserialize();
    }

    void global::UnityEngine.ISerializationCallbackReceiver.OnBeforeSerialize()
    {
        if (this is global::Alchemy.Serialization.IAlchemySerializationCallbackReceiver receiver)
            receiver.OnBeforeSerialize();
        SerializationCallback_AlchemyImpl(true);
    }

    protected void SerializationCallback_AlchemyImpl(bool isBeforeSerialize = false)
    {
        if (isBeforeSerialize)
        {
            InheritedSerializeTestBase1_alchemySerializationData.UnityObjectReferences.Clear();
            try
            {
                InheritedSerializeTestBase1_alchemySerializationData.set.data =
                    global::Alchemy.Serialization.Internal.SerializationHelper.ToJson(this.set,
                        InheritedSerializeTestBase1_alchemySerializationData.UnityObjectReferences);
                InheritedSerializeTestBase1_alchemySerializationData.set.isCreated = true;
            }
            catch (global::System.Exception ex)
            {
                global::UnityEngine.Debug.LogException(ex);
            }
        }
        else
        {
            try
            {
                if (InheritedSerializeTestBase1_alchemySerializationData.set.isCreated)
                {
                    this.set =
                        global::Alchemy.Serialization.Internal.SerializationHelper
                            .FromJson<System.Collections.Generic.HashSet<T>>(
                                InheritedSerializeTestBase1_alchemySerializationData.set.data,
                                InheritedSerializeTestBase1_alchemySerializationData.UnityObjectReferences);
                }
            }
            catch (global::System.Exception ex)
            {
                global::UnityEngine.Debug.LogException(ex);
            }
        }
    }

    [global::System.Serializable]
    sealed class AlchemySerializationData
    {
        public Item set = new();

        [global::UnityEngine.SerializeField]
        private global::System.Collections.Generic.List<UnityEngine.Object> unityObjectReferences = new();

        public global::System.Collections.Generic.IList<UnityEngine.Object> UnityObjectReferences =>
            unityObjectReferences;

        [global::System.Serializable]
        public sealed class Item
        {
            [global::UnityEngine.HideInInspector] public bool isCreated = false;
            [global::UnityEngine.TextArea(1, 999)] public string data;
        }
    }

    [global::UnityEngine.HideInInspector, global::UnityEngine.SerializeField]
    private AlchemySerializationData InheritedSerializeTestBase1_alchemySerializationData = new();
}
```

```cs
using System;
using Alchemy.Serialization;


[AlchemySerialize]
public partial class InheritedSerializeTest : InheritedSerializeTestBase<string>
{
    [AlchemySerializeField, NonSerialized] int? nullableInt;
}
```

```cs

// <auto-generated/>


partial class InheritedSerializeTest : global::UnityEngine.ISerializationCallbackReceiver
{
    void global::UnityEngine.ISerializationCallbackReceiver.OnAfterDeserialize()
    {
        SerializationCallback_AlchemyImpl(false);
        if (this is global::Alchemy.Serialization.IAlchemySerializationCallbackReceiver receiver)
            receiver.OnAfterDeserialize();
    }

    void global::UnityEngine.ISerializationCallbackReceiver.OnBeforeSerialize()
    {
        if (this is global::Alchemy.Serialization.IAlchemySerializationCallbackReceiver receiver)
            receiver.OnBeforeSerialize();
        SerializationCallback_AlchemyImpl(true);
    }

    protected new void SerializationCallback_AlchemyImpl(bool isBeforeSerialize = false)
    {
        base.SerializationCallback_AlchemyImpl(isBeforeSerialize);
        if (isBeforeSerialize)
        {
            InheritedSerializeTest_alchemySerializationData.UnityObjectReferences.Clear();
            try
            {
                InheritedSerializeTest_alchemySerializationData.nullableInt.data =
                    global::Alchemy.Serialization.Internal.SerializationHelper.ToJson(this.nullableInt,
                        InheritedSerializeTest_alchemySerializationData.UnityObjectReferences);
                InheritedSerializeTest_alchemySerializationData.nullableInt.isCreated = true;
            }
            catch (global::System.Exception ex)
            {
                global::UnityEngine.Debug.LogException(ex);
            }
        }
        else
        {
            try
            {
                if (InheritedSerializeTest_alchemySerializationData.nullableInt.isCreated)
                {
                    this.nullableInt = global::Alchemy.Serialization.Internal.SerializationHelper.FromJson<int?>(
                        InheritedSerializeTest_alchemySerializationData.nullableInt.data,
                        InheritedSerializeTest_alchemySerializationData.UnityObjectReferences);
                }
            }
            catch (global::System.Exception ex)
            {
                global::UnityEngine.Debug.LogException(ex);
            }
        }
    }

    [global::System.Serializable]
    sealed class AlchemySerializationData
    {
        public Item nullableInt = new();

        [global::UnityEngine.SerializeField]
        private global::System.Collections.Generic.List<UnityEngine.Object> unityObjectReferences = new();

        public global::System.Collections.Generic.IList<UnityEngine.Object> UnityObjectReferences =>
            unityObjectReferences;

        [global::System.Serializable]
        public sealed class Item
        {
            [global::UnityEngine.HideInInspector] public bool isCreated = false;
            [global::UnityEngine.TextArea(1, 999)] public string data;
        }
    }

    [global::UnityEngine.HideInInspector, global::UnityEngine.SerializeField]
    private AlchemySerializationData InheritedSerializeTest_alchemySerializationData = new();
}
```

### CODE REVIEW

**Comment by Akeit0** [comment]
This also works with class which doesn't have AlchemySerializeAttribute.
スクリーンショット 2024-03-03 011516

```cs
public  class InheritedSerializeTest : InheritedSerializeTestBase<string>
{
}
```

**Comment by Akeit0** [comment]
#53 #54

**Comment by AnnulusGames** [comment]
It looks very good! One thing, wouldn't it be more natural to split `SerializationCallback_AlchemyImpl` into two functions? Also, it would be better to put `__` at the beginning of the method name to prevent the method from showing up in the intellisense.

**Comment by AnnulusGames** [comment]
Sorry, just two more points.

The generated AlchemySerializationData field name should be `__alchemySerializationData_ClassName` instead of `ClassName_alchemySerializationData`.

Then, considering the Inspector's display when adding the ShowAllchemySerializationDataAttribute, add `Alchemy.Inspector.LabelText["Alchemy Serialization Data (ClassName )"]` would be even better.

**Comment by Akeit0** [comment]
> One thing, wouldn't it be more natural to split SerializationCallback_AlchemyImpl into two functions? Also, it would be better to put __ at the beginning of the method name to prevent the method from showing up in the intellisense.

OK, how about naming it __AlchemyOnBeforeSerialize/OnAfterDeserialize?

**Comment by Akeit0** [comment]
I fixed them
スクリーンショット 2024-03-21 114948


```cs
using System;
using Alchemy.Serialization;

namespace Test
{
    [ShowAlchemySerializationData]
    [AlchemySerialize]
    public partial class InheritedSerializeTest : InheritedSerializeTestBase<string>
    {
        [AlchemySerializeField, NonSerialized] int? nullableInt;
    }
}
```
```cs
// <auto-generated/>

namespace Test
{
    partial class InheritedSerializeTest : global::UnityEngine.ISerializationCallbackReceiver
    {
        void global::UnityEngine.ISerializationCallbackReceiver.OnAfterDeserialize()
        {
            __AlchemyOnAfterDeserialize();
            if (this is global::Alchemy.Serialization.IAlchemySerializationCallbackReceiver receiver) receiver.OnAfterDeserialize();
        }

        void global::UnityEngine.ISerializationCallbackReceiver.OnBeforeSerialize()
        {
            if (this is global::Alchemy.Serialization.IAlchemySerializationCallbackReceiver receiver) receiver.OnBeforeSerialize();
            __AlchemyOnBeforeSerialize();
        }


        protected new void __AlchemyOnAfterDeserialize()
        {
            base.__AlchemyOnAfterDeserialize();
            try
            {
                if (__alchemySerializationData_Test_InheritedSerializeTest.nullableInt.isCreated)
                {
                    this.nullableInt = global::Alchemy.Serialization.Internal.SerializationHelper.FromJson<int?>(__alchemySerializationData_Test_InheritedSerializeTest.nullableInt.data, __alchemySerializationData_Test_InheritedSerializeTest.UnityObjectReferences);
                }
            }
            catch (global::System.Exception ex)
            {
                global::UnityEngine.Debug.LogException(ex);
            }
        }

        protected new void __AlchemyOnBeforeSerialize()
        {
            base.__AlchemyOnBeforeSerialize();
            __alchemySerializationData_Test_InheritedSerializeTest.UnityObjectReferences.Clear();
            try
            {
                __alchemySerializationData_Test_InheritedSerializeTest.nullableInt.data = global::Alchemy.Serialization.Internal.SerializationHelper.ToJson(this.nullableInt, __alchemySerializationData_Test_InheritedSerializeTest.UnityObjectReferences);
                __alchemySerializationData_Test_InheritedSerializeTest.nullableInt.isCreated = true;
            }
            catch (global::System.Exception ex)
            {
                global::UnityEngine.Debug.LogException(ex);
            }
        }

        [global::System.Serializable]
        sealed class AlchemySerializationData
        {
            public Item nullableInt = new();

            [global::UnityEngine.SerializeField] private global::System.Collections.Generic.List<UnityEngine.Object> unityObjectReferences = new();
            public global::System.Collections.Generic.IList<UnityEngine.Object> UnityObjectReferences => unityObjectReferences;

            [global::System.Serializable]
            public sealed class Item
            {
                [global::UnityEngine.HideInInspector] public bool isCreated = false;
                [global::UnityEngine.TextArea(1, 999)] public string data;
            }
        }

        [global::Alchemy.Inspector.LabelText("Alchemy Serialization Data (Test.InheritedSerializeTest)"), global::Alchemy.Inspector.ReadOnly, global::UnityEngine.TextArea(3, 999), global::UnityEngine.SerializeField]
        private AlchemySerializationData __alchemySerializationData_Test_InheritedSerializeTest = new();
    }
}
```

**Comment by AnnulusGames** [comment]
I have confirmed that it works on my end. Can I merge this PR already?

**Comment by AnnulusGames** [comment]
Merged PR. Thank you!

**Pull request merged**
