### PR TITLE
Add: tree map and row separator for hierarchy

### PR DESCRIPTION
**Pull request by yenmoc**
image
image

### CODE REVIEW

**Comment by AnnulusGames** [comment]
Generally there is no problem, but there is one problem: the default color of the tree map is difficult to see in light skins. One idea to solve this problem is to remove the color setting for the tree map and change the color to a different color for each skin.

**Comment by yenmoc** [comment]
> Generally there is no problem, but there is one problem: the default color of the tree map is difficult to see in light skins. One idea to solve this problem is to remove the color setting for the tree map and change the color to a different color for each skin.

Ya, because I haven't used light skin in a long time. I think creating an additional data class to contain separate colors for each theme and adjusting the default color for each theme would be more reasonable. The downside is that instead of using Color, we have to use the class. the other wrapper to declare. What do you think?

**Comment by yenmoc** [comment]
> Generally there is no problem, but there is one problem: the default color of the tree map is difficult to see in light skins. One idea to solve this problem is to remove the color setting for the tree map and change the color to a different color for each skin.

I wonder if removing color customization and using default colors in addition to reducing personalization is a good idea? I'm quite confused

**Comment by AnnulusGames** [comment]
> I wonder if removing color customization and using default colors in addition to reducing personalization is a good idea? I'm quite confused. Personally, I always use the default color

Well, that's true. Considering the hassle of implementation and the large number of settings, it may be better to leave it as it is. In that case, changing the color to (0.7, 0.7, 0.7, 1.0) made it easy to see in both skins, so how about changing the default to a color close to that?

One more thing, I noticed while making some adjustments, but the drop shadow of the tree texture doesn't seem to fit the flat design editor. I think it would be better to make it closer to flat, but what do you think? (It looks blurred especially in the light skin.)

**Comment by yenmoc** [comment]
> > I wonder if removing color customization and using default colors in addition to reducing personalization is a good idea? I'm quite confused. Personally, I always use the default color
> 
> Well, that's true. Considering the hassle of implementation and the large number of settings, it may be better to leave it as it is. In that case, changing the color to (0.7, 0.7, 0.7, 0.7) made it easy to see in both skins, so how about changing the default to a color close to that?
> 
> One more thing, I noticed while making some adjustments, but the drop shadow of the tree texture doesn't seem to fit the flat design editor. I think it would be better to make it closer to flat, but what do you think? (It looks blurred especially in the light skin.)

Well they look quite annoying, I'll try redesigning the image side, surprisingly they blend well in the dark theme

**Comment by AnnulusGames** [comment]
I checked it out. It looks great!

One last thing: these features are set to true by default, but I think it would be better to set them to false. (One of Alchemy's design principles is to unify the behavior of the standard Unity editor unless you change the settings, and changing the hierarchy display as soon as you install it goes against this idea.)

**Comment by yenmoc** [comment]
Now, Additional features are disabled by default

**Comment by AnnulusGames** [comment]
Confirmed. Is it okay to merge the PR?

**Comment by yenmoc** [comment]
I think everything is ready for that

**Comment by AnnulusGames** [comment]
Merged PR!

**Pull request merged**
